#!/bin/sh

git config --global alias.last "cat-file commit HEAD"
git config --global alias.stc "diff --stat --name-status --cached"
git config --global alias.up "!git remote update ; git gc"
git config --global alias.log1 "log --pretty=oneline --abbrev-commit --decorate"
git config --global alias.lg "log -n 20 --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset %an' --abbrev-commit --date=relative"
